/*
 * keyboard_buttons.h
 *
 *  Created on: Jun 28, 2025
 *      Author: UnikoZera
 */

#ifndef INC_KEYBOARD_BUTTONS_H_
#define INC_KEYBOARD_BUTTONS_H_

#define KEYBOARD_BUTTON_NONE 0x00

// USB HID的协议是第0位为特殊按键
// (Left Ctrl, Left Shift, Left Alt, Left GUI, Right Ctrl, Right Shift, Right Alt, Right GUI)
#define KEYBOARD_BUTTON_LEFT_CTRL 0x01
#define KEYBOARD_BUTTON_LEFT_SHIFT 0x02
#define KEYBOARD_BUTTON_LEFT_ALT 0x03
#define KEYBOARD_BUTTON_LEFT_GUI 0x04
#define KEYBOARD_BUTTON_RIGHT_CTRL 0x05
#define KEYBOARD_BUTTON_RIGHT_SHIFT 0x06
#define KEYBOARD_BUTTON_RIGHT_ALT 0x07
#define KEYBOARD_BUTTON_RIGHT_GUI 0x08

// 标准的26个按键
#define KEYBOARD_BUTTON_A 0x04
#define KEYBOARD_BUTTON_B 0x05
#define KEYBOARD_BUTTON_C 0x06
#define KEYBOARD_BUTTON_D 0x07
#define KEYBOARD_BUTTON_E 0x08
#define KEYBOARD_BUTTON_F 0x09
#define KEYBOARD_BUTTON_G 0x0A
#define KEYBOARD_BUTTON_H 0x0B
#define KEYBOARD_BUTTON_I 0x0C
#define KEYBOARD_BUTTON_J 0x0D
#define KEYBOARD_BUTTON_K 0x0E
#define KEYBOARD_BUTTON_L 0x0F
#define KEYBOARD_BUTTON_M 0x10
#define KEYBOARD_BUTTON_N 0x11
#define KEYBOARD_BUTTON_O 0x12
#define KEYBOARD_BUTTON_P 0x13
#define KEYBOARD_BUTTON_Q 0x14
#define KEYBOARD_BUTTON_R 0x15
#define KEYBOARD_BUTTON_S 0x16
#define KEYBOARD_BUTTON_T 0x17
#define KEYBOARD_BUTTON_U 0x18
#define KEYBOARD_BUTTON_V 0x19
#define KEYBOARD_BUTTON_W 0x1A
#define KEYBOARD_BUTTON_X 0x1B
#define KEYBOARD_BUTTON_Y 0x1C
#define KEYBOARD_BUTTON_Z 0x1D


#endif /* INC_KEYBOARD_BUTTONS_H_ */
